package com.example.kchat.feature.smartreply

/**
 * Encapsulates the conversational intelligence analysis and reply suggestions
 * generated by the Gemini model for KChat Smart Reply.
 */
data class SmartReplyResult(
    val tone: String = "Neutral",
    val sentiment: String = "Neutral",
    val intent: String = "Conversation",
    val urgency: String = "Normal",
    val suggestions: List<String> = emptyList()
)
