package com.example.kchat.feature.threadsummary

/**
 * Encapsulates the structured conversational summary generated by Gemini
 * for KChat Smart Thread Summarization.
 */
data class ThreadSummaryResult(
    val keyPoints: List<String> = emptyList(),
    val decisions: List<String> = emptyList(),
    val tasks: List<String> = emptyList(),
    val deadlines: List<String> = emptyList(),
    val importantDetails: List<String> = emptyList()
) {
    val isEmpty: Boolean
        get() = keyPoints.isEmpty() && decisions.isEmpty() && tasks.isEmpty() && deadlines.isEmpty() && importantDetails.isEmpty()

    /**
     * Formats the summary into readable plain text suitable for copying to clipboard.
     */
    fun toFormattedText(): String = buildString {
        appendLine("📋 KChat Thread Summary")
        appendLine()
        if (keyPoints.isNotEmpty()) {
            appendLine("📌 Key Points:")
            keyPoints.forEach { appendLine("• $it") }
            appendLine()
        }
        if (decisions.isNotEmpty()) {
            appendLine("🎯 Decisions:")
            decisions.forEach { appendLine("• $it") }
            appendLine()
        }
        if (tasks.isNotEmpty()) {
            appendLine("📋 Tasks / Action Items:")
            tasks.forEach { appendLine("• $it") }
            appendLine()
        }
        if (deadlines.isNotEmpty()) {
            appendLine("⏰ Deadlines & Dates:")
            deadlines.forEach { appendLine("• $it") }
            appendLine()
        }
        if (importantDetails.isNotEmpty()) {
            appendLine("ℹ️ Important Details:")
            importantDetails.forEach { appendLine("• $it") }
            appendLine()
        }
    }.trim()
}
